// Commandes du terminal — logique séparée de l'UI pour testabilité
// Chaque commande reçoit la langue courante et retourne string | string[]

import type { Lang } from "@/hooks/useLang";

type CommandHandler = (lang: Lang) => string | string[];
type Commands = Record<string, CommandHandler>;

export const terminalCommands: Commands = {
  help: (lang) =>
    lang === "fr"
      ? [
          "╔═══════════════════════════════════════╗",
          "║       TERMINAL ISSA KANE v1.0         ║",
          "╚═══════════════════════════════════════╝",
          "",
          "  whoami      → Qui suis-je ?",
          "  projects    → Mes 4 projets",
          "  stack       → Stack technique complète",
          "  xp          → Expérience professionnelle",
          "  contact     → Me contacter",
          "  clear        → Vider le terminal",
          "  exit         → Fermer le terminal",
          "",
          "  Astuce : Tab pour l'autocomplétion, ↑↓ pour l'historique",
        ]
      : [
          "╔═══════════════════════════════════════╗",
          "║       ISSA KANE TERMINAL v1.0         ║",
          "╚═══════════════════════════════════════╝",
          "",
          "  whoami      → Who am I?",
          "  projects    → My 4 projects",
          "  stack       → Full tech stack",
          "  xp          → Work experience",
          "  contact     → Get in touch",
          "  clear        → Clear terminal",
          "  exit         → Close terminal",
          "",
          "  Tip: Tab for autocomplete, ↑↓ for history",
        ],

  whoami: (lang) =>
    lang === "fr"
      ? [
          "┌─────────────────────────────────────────┐",
          "│  Issa KANE                              │",
          "│  Ingénieur IA & Data                    │",
          "│  EFREI Paris — Master 1                 │",
          "│  22 ans — Villejuif (94800)             │",
          "│  Alternance dès février 2026            │",
          "│  3j entreprise / 2j école               │",
          "└─────────────────────────────────────────┘",
          "",
          "  Né au Sénégal 🌍 — Bac S mention AB à Dakar",
          "  Ingénieur SI chez SFR pendant 2 ans",
          "  \"J'transforme des données brutes en systèmes intelligents.\"",
        ]
      : [
          "┌─────────────────────────────────────────┐",
          "│  Issa KANE                              │",
          "│  AI & Data Engineer                     │",
          "│  EFREI Paris — Master 1                 │",
          "│  22 years old — Villejuif (94800)       │",
          "│  Apprenticeship from February 2026      │",
          "│  3 days company / 2 days school         │",
          "└─────────────────────────────────────────┘",
          "",
          "  Born in Senegal 🌍 — High school diploma with honors in Dakar",
          "  Systems engineer at SFR for 2 years",
          "  \"I turn raw data into intelligent systems.\"",
        ],

  projects: (lang) =>
    lang === "fr"
      ? [
          "── PROJETS ──────────────────────────────────",
          "",
          "  [1] PetFinder — Full-stack web",
          "      Spring Boot + MyBatis + Vue.js + SQL",
          "      Plateforme d'adoption avec recherche temps réel",
          "",
          "  [2] Système de reco livres — IA & Data",
          "      Python + NLP + TF-IDF + Filtrage collaboratif",
          "      Double approche content-based + collaborative",
          "",
          "  [3] Recommandations en C — Autodidacte",
          "      C pur + structures de données + algos custom",
          "      Analyse d'humeur → suggestions films/livres",
          "",
          "  [4] App SI SFR — Prod réelle ⭐",
          "      Python/Flask + Kafka + Elasticsearch + ML + Prometheus",
          "      Pipeline complet, présenté à la direction SFR",
          "",
          "  → Tapez 'xp' pour plus de détails sur le projet SFR",
        ]
      : [
          "── PROJECTS ─────────────────────────────────",
          "",
          "  [1] PetFinder — Full-stack web",
          "      Spring Boot + MyBatis + Vue.js + SQL",
          "      Adoption platform with real-time search",
          "",
          "  [2] Book Recommendation System — AI & Data",
          "      Python + NLP + TF-IDF + Collaborative Filtering",
          "      Dual content-based + collaborative approach",
          "",
          "  [3] Recommendations in C — Self-taught",
          "      Pure C + data structures + custom algorithms",
          "      Mood analysis → movie/book suggestions",
          "",
          "  [4] SFR IS App — Real Production ⭐",
          "      Python/Flask + Kafka + Elasticsearch + ML + Prometheus",
          "      Full pipeline, presented to SFR management",
          "",
          "  → Type 'xp' for more details on the SFR project",
        ],

  stack: (lang) =>
    lang === "fr"
      ? [
          "── STACK TECHNIQUE ──────────────────────────",
          "",
          "  LANGAGES",
          "  Python · Java · C · SQL · TypeScript · PHP · Swift · Kotlin",
          "",
          "  FRAMEWORKS",
          "  Flask · Spring Boot · Vue.js · Next.js · Laravel",
          "  LangChain · LangGraph  ← IA générative",
          "",
          "  DATA & IA",
          "  Pandas · Scikit-learn · NLP · TF-IDF",
          "  Filtrage collaboratif · Détection d'anomalies · ML pipelines",
          "",
          "  BIG DATA",
          "  Kafka · Elasticsearch · Spark / PySpark",
          "",
          "  BASES DE DONNÉES",
          "  MySQL · PostgreSQL · MongoDB · MyBatis",
          "",
          "  SYSTÈMES",
          "  Linux · Bash · Windows Server · NFS · Active Directory",
          "",
          "  DEVOPS & MONITORING",
          "  Docker · Git/GitHub · Prometheus · Grafana",
          "",
          "  CE PORTFOLIO",
          "  Next.js 14 · TypeScript · Tailwind · Framer Motion",
          "  Three.js · GLSL · Shiki · Monaco Editor",
        ]
      : [
          "── TECH STACK ───────────────────────────────",
          "",
          "  LANGUAGES",
          "  Python · Java · C · SQL · TypeScript · PHP · Swift · Kotlin",
          "",
          "  FRAMEWORKS",
          "  Flask · Spring Boot · Vue.js · Next.js · Laravel",
          "  LangChain · LangGraph  ← Generative AI",
          "",
          "  DATA & AI",
          "  Pandas · Scikit-learn · NLP · TF-IDF",
          "  Collaborative filtering · Anomaly detection · ML pipelines",
          "",
          "  BIG DATA",
          "  Kafka · Elasticsearch · Spark / PySpark",
          "",
          "  DATABASES",
          "  MySQL · PostgreSQL · MongoDB · MyBatis",
          "",
          "  SYSTEMS",
          "  Linux · Bash · Windows Server · NFS · Active Directory",
          "",
          "  DEVOPS & MONITORING",
          "  Docker · Git/GitHub · Prometheus · Grafana",
          "",
          "  THIS PORTFOLIO",
          "  Next.js 14 · TypeScript · Tailwind · Framer Motion",
          "  Three.js · GLSL · Shiki · Monaco Editor",
        ],

  xp: (lang) =>
    lang === "fr"
      ? [
          "── EXPÉRIENCE ───────────────────────────────",
          "",
          "  ★ Ingénieur SI — SFR Paris",
          "    Août 2023 → Août 2025  (2 ans, Alternance)",
          "",
          "    ● App web Python/Flask : suivi performance SI",
          "    ● Pipeline Kafka → Elasticsearch (de zéro)",
          "    ● Monitoring Prometheus en production",
          "    ● Intégration ML : détection d'anomalies temps réel",
          "    ● Présentation à la direction SFR ← projet stratégique",
          "",
          "    Architecture : Flask REST → Kafka Broker → ES Index",
          "                  → Scikit-learn model → Prometheus metrics",
          "",
          "  ○ Téléprospecteur — SFR Paris",
          "    Janvier 2022 → Février 2022  (Stage)",
          "    500 appels/jour · Collecte exigences PME",
        ]
      : [
          "── EXPERIENCE ───────────────────────────────",
          "",
          "  ★ Systems Engineer — SFR Paris",
          "    August 2023 → August 2025  (2 years, Apprenticeship)",
          "",
          "    ● Python/Flask web app: IS performance tracking",
          "    ● Kafka → Elasticsearch pipeline (from scratch)",
          "    ● Prometheus monitoring in production",
          "    ● ML integration: real-time anomaly detection",
          "    ● Presented to SFR management ← strategic project",
          "",
          "    Architecture: Flask REST → Kafka Broker → ES Index",
          "                  → Scikit-learn model → Prometheus metrics",
          "",
          "  ○ Teleprospector — SFR Paris",
          "    January 2022 → February 2022  (Internship)",
          "    500 calls/day · Collecting SMB requirements",
        ],

  contact: (lang) =>
    lang === "fr"
      ? [
          "── CONTACT ──────────────────────────────────",
          "",
          "  Email    →  issa.kane@efrei.net",
          "  GitHub   →  github.com/issadevs",
          "  LinkedIn →  linkedin.com/in/issakane",
          "  Tél      →  06 52 52 72 14",
          "",
          "  Disponible dès février 2026",
          "  Rythme : 3j entreprise / 2j école",
          "  Localisation : Villejuif (94800), Île-de-France",
        ]
      : [
          "── CONTACT ──────────────────────────────────",
          "",
          "  Email    →  issa.kane@efrei.net",
          "  GitHub   →  github.com/issadevs",
          "  LinkedIn →  linkedin.com/in/issakane",
          "  Phone    →  +33 6 52 52 72 14",
          "",
          "  Available from February 2026",
          "  Schedule: 3 days company / 2 days school",
          "  Location: Villejuif (94800), Île-de-France",
        ],

  // Easter egg secret — non listé dans help
  dakar: (_lang) => [
    "",
    "  ██████████████████████████████████████████",
    "  ██        ██████████████████████████████ ██",
    "  ██  VERT  ██        JAUNE        ██  R  ██",
    "  ██        ██  ★ SÉNÉGAL ★       ██  O  ██",
    "  ██        ██████████████████████████  U  ██",
    "  ██████████████████████████████████████  G  ██",
    "  ████████████████████████████████████  E  ██",
    "  ██████████████████████████████████████████",
    "",
    "  🌍 Né à Dakar, Sénégal",
    "  Bac scientifique mention Assez Bien",
    "  Parti étudier à EFREI Paris — Classe prépa intégrée",
    "",
    "  \"Le Sénégal m'a appris la résilience.",
    "   Paris m'a appris l'ingénierie.",
    "   Les deux font qui je suis.\"",
    "",
    "  Teranga 🤝",
    "",
  ],
};
